[Tamna] 숙소 전체리스트 API
wecode-bootcamp-korea/34-2nd-TamnaBnB-backend pull request #5
Opened 2022-07-08 09:55 UTC by sangwoong03

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [x] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [x] 컨벤션 수정

<br />

## :: 구현 목표

숙소 전체 리스트 정보를 보내주고, 특정 조건에 따른 필터링이 가능한 API 구현

<br />

## :: 구현 사항 설명

메인 페이지에서 전체 숙소 리스트를 보여주는 API작성

1. 전체 숙소 리스트 보여주기
2. 필터링을 통해 조건에 맞는 숙소 보여주기
필터링 조건은 다음과 같습니다:
- 체크인/체크아웃 날짜 ==> Q() 객체를 활용하여 reservation 테이블에 포함된 날짜라면 제외하여 필터링
- filter_set 객체를 활용하여 지역, 침대(침실), 가격, 인원수, 숙소타입, 카테고리 별 필터링 적용

3. ORM 최적화를 위해 select_related(), prefetch_related()를 활용
4. annotate()를 활용하여 review 테이블의 ratings(평점) 데이터 평균 가져오기 적용

<br />

## :: 성장 포인트

1. Q(), filter_set 객체를 통해 특정 조건에 맞는 데이터를 필터링하는 것을 공부하였습니다.
2. annotate() 함수의 사용 방법을 알게되었습니다.
3. ORM 최적화를 위해 select_related()와 prefetch_related() 메서드 활용 방법을 적용해보고 이해할 수 있었습니다.

<br />

## :: 기타 질문 및 특이 사항
1. (답변 완료)
날짜 필터링과 관련해서 질문이 있습니다.
예약 테이블에 정보가 있고, 예약이 되어 있는지의 여부를 판단을 해야 날짜별 필터링이 가능할 것 같다고 생각이 되는데 어떻게 생각하시는지 궁금합니다.

## 테스트 코드 결과 사진 (필터링 테스트 코드 추가)
<img width="370" alt="image" src="https://user-images.githubusercontent.com/93123657/178146483-4dd6b7c6-ecf6-454e-b198-f8aea0b0a0b2.png">

2022-07-08 10:00 UTC, bigfanoftim commented
> 예약 테이블에 정보가 있고, 예약이 되어 있는지의 여부를 판단을 해야 날짜별 필터링이 가능할 것 같다고 생각이 되는데 어떻게 생각하시는지 궁금합니다.

맞습니다. 따라서 예약 데이터가 있어야 필터링을 제대로 테스트할 수 있습니다!

2022-07-08 10:00 UTC, bigfanoftim requested changes

2022-07-08 10:00 UTC, bigfanoftim commented on tamnabnb/urls.py
> +<<<<<<< HEAD
rebase 찌거기 👀

2022-07-08 10:09 UTC, sangwoong03 commented on tamnabnb/urls.py
> +<<<<<<< HEAD
수정하겠습니다.

2022-07-11 02:55 UTC, bigfanoftim approved these changes
LGTM 👍

2022-07-11 02:55 UTC, merged